#!/usr/bin/python

import sys

path = sys.argv[1]
print "path is " + path

with open(path) as f:
  lines = f.read()
  print "commit message is"
  print lines
  if "hello world" in lines:
    print "format test passed"
    exit(0)
  else:
    print "format test failed"
    exit(1)
